[tool.poetry]
package-mode = false

[project]
name = "ex1"
requires-python = ">=3.12"
dependencies = [
    "pandas (==3.0.0)",
    "requests (==2.31.0)",
    "matplotlib (==3.7.2)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
